<?php

/**
 * Set the basic environment settings like encryption key and
 * debug mode
 */
if(getenv('SECRET_KEY')) {
    // Set static secret if present, otherwise use autogenerated random value from .env
    $env['APP_SECRET'] = 'base64:'. base64_encode(substr(getenv('SECRET_KEY'), 0, 32));
}
$env['APP_DEBUG'] = $_SERVER['DEBUG'] ?? true;
$env['APP_ENV'] = $_SERVER['STAGE'] ?? 'dev';

/**
 * set default logging output to stderr
 */
$env['LOG_CHANNEL'] = 'stderr';

$env['DATABASE_URL'] = preg_replace('/^postgres:\/\//', 'pgsql://', $_SERVER['DEFAULT_DATABASE_DSN'] ?? 'postgres://postgres@db:5432/db');

/**
 * get the storage dsn and translate it into different
 * environment variables
 */
if(isset($_SERVER['DEFAULT_STORAGE_DSN'])) {

    $s3 = parse_url($_SERVER['DEFAULT_STORAGE_DSN']);
    parse_str($s3['query'], $query);

    $env['FILESYSTEM_DRIVER'] = 's3';
    $env['AWS_ACCESS_KEY_ID'] = $s3['user'];
    $env['AWS_SECRET_ACCESS_KEY'] = urldecode($s3['pass']);
    $env['AWS_BUCKET'] = $query['domain'];

    /**
     * Symfony uses phpleague/flysystem to connect to S3. Due to configuration
     * limitation it is not possible to launch the multiregion client instead of
     * AWS\S3\S3Client which requires the (expandable) AWS_REGION to be set. We
     * therefore try to set it manually and (sadly) ugly :(
     */
    if(strstr($s3['host'], "s3.amazonaws.com") !== false) {
        $env['AWS_REGION'] = str_replace([$query['domain'], 's3.amazonaws.com', '.'], '', $s3['host']) ?: 'us-east-1';
    }
}

/**
 * Set environment variables in $_ENV and the environment
 */
foreach($env as $key => $value) {
    $_ENV[$key] = $value;
    putenv($key .'='. $value);
}
